NUM_GPUS: 1
NUM_NODES: 1
RANK_ID: 0
DIST_BACKEND: "nccl"
RNG_SEED: 1
OUTPUT_DIR: 'outputs/ofd/ofd_r50_pret_mbv2_c100_224_e100_sgd_mslr_lam_1e-6'
TRAIN:
  LOG_STEP: 10
  GRADIENT_ACCUMULATE_STEP: 1
  MAX_EPOCH: 100
  SAVE_EPOCH: 1
  EVAL_EPOCH: 1
  RESUME: False
  USE_TENSORBOARD: True
  HYBRID_PRECISION: True
DATASET:
  NAME: 'CIFAR100'
  TRAIN_ROOT: './data/cifar'
  TEST_ROOT: './data/cifar'
  TOP_K: (1, 5)
TRANSFORM:
  TRAIN_METHODS: ('Resize', 'RandomCrop', 'RandomHorizontalFlip', 'AUTO_AUGMENT', 'ToTensor', 'Normalize')
  TEST_METHODS: ('Resize', 'CenterCrop', 'ToTensor', 'Normalize')
  TRAIN_RESIZE: (256, )
  TEST_RESIZE: (224, )
  TRAIN_CROP: (224, 224)
  TEST_CROP: (224, 224)
  AUGMENT_POLICY: "cifar10"
  MEAN: (0.45, 0.45, 0.45)
  STD: (0.225, 0.225, 0.225)
DATALOADER:
  TRAIN_BATCH_SIZE: 128
  TEST_BATCH_SIZE: 128
  NUM_WORKERS: 4
  RANDOM_SAMPLE: True
  PREFETCHER: True
DISTILL:
  T_ARCH: 'resnet50'
  T_NUM_CLASSES: 100
  T_PRELOADED: 'outputs/benchmark/r50_c100_224_e100_sgd_mslr/model_0096.pth'
  S_ARCH: 'mobilenet_v2'
  S_NUM_CLASSES: 100
  S_PRELOADED: ''
  DISTILLER: 'OFD'
  LAMBDA: 1e-6
MODEL:
  CRITERION:
    NAME: 'OFDLoss'
OPTIMIZER:
  NAME: 'SGD'
  LR: 0.05
  MOMENTUM: 0.9
  WEIGHT_DECAY:
    DECAY: 4e-5
    NO_BIAS: True
    NO_NORM: True
LR_SCHEDULER:
  NAME: 'MultiStepLR'
  IS_WARMUP: True
  GAMMA: 0.1
  MULTISTEP_LR:
    MILESTONES: [ 40, 60, 80 ]
  WARMUP:
    ITERATION: 5
    MULTIPLIER: 1.0