NUM_GPUS: 1
NUM_NODES: 1
RANK_ID: 0
DIST_BACKEND: "nccl"
RNG_SEED: 1
OUTPUT_DIR: 'outputs/benchmark/r50_c100_224_e100_sgd_mslr'
TRAIN:
  LOG_STEP: 10
  GRADIENT_ACCUMULATE_STEP: 1
  MAX_EPOCH: 100
  SAVE_EPOCH: 1
  EVAL_EPOCH: 1
  RESUME: False
  USE_TENSORBOARD: True
  HYBRID_PRECISION: True
DATASET:
  NAME: 'CIFAR100'
  TRAIN_ROOT: './data/cifar'
  TEST_ROOT: './data/cifar'
  TOP_K: (1, 5)
TRANSFORM:
  TRAIN_METHODS: ('Resize', 'RandomCrop', 'HorizontalFlip', 'AutoAugment', 'Normalize', 'ToTensor')
  TEST_METHODS: ('Resize', 'CenterCrop', 'Normalize', 'ToTensor')
  TRAIN_RESIZE: ((256, ), 1, 0, 1.0)
  TEST_RESIZE: ((224, ), 1, 0, 1.0)
  TRAIN_CENTER_CROP: ((224, 224), 1.0)
  TEST_CENTER_CROP: ((224, 224), 1.0)
  AUTOAUGMENT: ("cifar10", 1.0)
  NORMALIZE: ((0.45, 0.45, 0.45), (0.225, 0.225, 0.225), 255.0, 1.0)
  TO_TENSOR: 1.0
DATALOADER:
  TRAIN_BATCH_SIZE: 128
  TEST_BATCH_SIZE: 128
  NUM_WORKERS: 4
  RANDOM_SAMPLE: True
  PREFETCHER: True
DISTILL:
#  T_ARCH: 'resnet50'
#  T_NUM_CLASSES: 1000
#  T_PRELOADED: ''
  S_ARCH: 'resnet50'
  S_NUM_CLASSES: 100
  S_PRELOADED: ''
  DISTILLER: ''
MODEL:
  CRITERION:
    NAME: 'LabelSmoothingLoss'
    SMOOTHING: 0.1
    REDUCTION: 'mean'
OPTIMIZER:
  NAME: 'SGD'
  LR: 0.05
  MOMENTUM: 0.9
  WEIGHT_DECAY:
    DECAY: 1e-4
    NO_BIAS: False
    NO_NORM: False
LR_SCHEDULER:
  NAME: 'MultiStepLR'
  IS_WARMUP: True
  GAMMA: 0.1
  MULTISTEP_LR:
    MILESTONES: [ 30, 60, 90 ]
  WARMUP:
    ITERATION: 5
    MULTIPLIER: 1.0